index:
    path: /
    controller: App\Controller\MenuController::index

show:
    path: /WyswietlUmowy
    controller: App\Controller\MenuController::showUmowy

showObiektyNajmu:
    path: /WyswietlObiektyNajmu
    controller: App\Controller\MenuController::showObiektyNajmu

showBudynki:
    path: /WyswietlBudynki
    controller: App\Controller\MenuController::showBudynki

showOsoby:
    path: /WyswietlOsoby
    controller: App\Controller\MenuController::showOsoby

showSpoldzielnie:
    path: /WyswietlSpoldzielnie
    controller: App\Controller\MenuController::showSpoldzielnie

showWyposazenie:
    path: /WyswietlWyposazenie
    controller: App\Controller\MenuController::showWyposazenie

showZwierzeta:
    path: /WyswietlZwierzeta
    controller: App\Controller\MenuController::showZwierzeta

newOsoba:
    path: /NowaOsoba
    controller: App\Controller\MenuController::newOsoba

newBudynek:
    path: /NowyBudynek
    controller: App\Controller\MenuController::newBudynek

newObiektNajmu:
    path: /NowyObiektNajmu
    controller: App\Controller\MenuController::newObiektNajmu 

newSpoldzielnia:
    path: /NowaSpoldzielnia
    controller: App\Controller\MenuController::newSpoldzielnia 

newUmowa:
    path: /NowaUmowa
    controller: App\Controller\MenuController::newUmowa 

newWyposazenie:
    path: /NoweWyposazenie
    controller: App\Controller\MenuController::newWyposazenie 

newZwierze:
    path: /NoweZwierze
    controller: App\Controller\MenuController::newZwierze 
    